version: "3.8"
services:
  php:
    build:
      context: ./src
      dockerfile: ../docker/php/php.Dockerfile
    volumes:
      - ./src:/var/www/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel-network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: nginx.Dockerfile
    ports:
      - "8051:80"
    volumes:
      - ./src:/var/www/app
    depends_on:
      - php
    networks:
      - laravel-network

  db:
    build:
      context: ./docker/mysql
      dockerfile: mysql.Dockerfile
    command: --innodb-data-file-path=/ibdata1:100M:autoextend
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: paulkusuma
      MYSQL_PASSWORD: pauwerfull
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.51.0.0/24

volumes:
  mysql-data:
    driver: local
